## Project 1: Basic Data Analysis on a NumPy Array

In [1]:
import numpy as np

# 1. Create a Sample Array
# A 2D array with 5 rows (samples) and 4 columns (features)
arr = np.random.randint(10, 100, size=(5, 4))
print("Original Array:\n", arr)

# 2. Calculations
# Mean of each column
column_mean = arr.mean(axis=0)
print("\nMean of each column:", column_mean)

# Maximum value in each row
row_max = arr.max(axis=1)
print("Maximum value in each row:", row_max)

# Total sum of all elements
total_sum = arr.sum()
print("Total sum of all elements:", total_sum)

# 3. Indexing
# First two rows and last two columns
selected_part = arr[0:2, 2:4]
print("\nFirst two rows and last two columns:\n", selected_part)

# Boolean indexing – values greater than 50
greater_than_50 = arr[arr > 50]
print("\nElements greater than 50:", greater_than_50)


Original Array:
 [[17 24 44 93]
 [78 56 59 67]
 [53 90 82 73]
 [65 97 44 14]
 [32 20 49 19]]

Mean of each column: [49.  57.4 55.6 53.2]
Maximum value in each row: [93 78 90 97 49]
Total sum of all elements: 1076

First two rows and last two columns:
 [[44 93]
 [59 67]]

Elements greater than 50: [93 78 56 59 67 53 90 82 73 65 97]
