# Project 1: Data Normalization

In [1]:
import numpy as np

# Create a 2D array (5 samples, 4 features)
arr = np.random.randint(10, 100, (5, 4))
print("Original Array:\n", arr)

# Calculate mean and standard deviation for each column
mean = arr.mean(axis=0)
std = arr.std(axis=0)

# Normalize: (value - mean) / std
normalized_arr = (arr - mean) / std

print("\nMean of each column:", mean)
print("Standard Deviation of each column:", std)
print("\nNormalized Array:\n", normalized_arr)


Original Array:
 [[45 25 33 20]
 [58 34 28 70]
 [37 60 99 94]
 [57 30 85 27]
 [87 62 29 25]]

Mean of each column: [56.8 42.2 54.8 47.2]
Standard Deviation of each column: [16.99882349 15.62561999 30.74020169 29.49847454]

Normalized Array:
 [[-0.69416569 -1.10075632 -0.70916906 -0.92208158]
 [ 0.07059312 -0.52477918 -0.87182252  0.77292132]
 [-1.16478649  1.1391548   1.43785654  1.58652272]
 [ 0.01176552 -0.78076902  0.98242687 -0.68478117]
 [ 1.77659354  1.26714972 -0.83929183 -0.75258129]]
